---
- project:
    name: packit-service/dashboard
    check:
      jobs:
        - pre-commit
        # - dashboard-tests
    gate:
      jobs:
        - pre-commit
# - job:
#     name: dashboard-tests
#     parent: base
#     description: Run tests
#     pre-run:
#       - files/zuul-install-requirements.yaml
#     run: files/zuul-tests.yaml
#     extra-vars:
#       ansible_python_interpreter: /usr/bin/python3
#     nodeset:
#       nodes:
#         - name: test-node
#           label: cloud-fedora-31
