---
- project:
    name: packit-service/dashboard
    check:
      jobs:
        - dashboard-pre-commit
        # - dashboard-tests
    gate:
      jobs:
        - dashboard-pre-commit

- job:
    name: dashboard-pre-commit
    parent: base
    description: Check precommit
    run: files/zuul-pre-commit.yaml
    extra-vars:
      ansible_python_interpreter: /usr/bin/python3
    nodeset:
      nodes:
        - name: test-node
          label: cloud-fedora-31
# - job:
#     name: dashboard-tests
#     parent: base
#     description: Run tests
#     pre-run:
#       - files/zuul-install-requirements.yaml
#     run: files/zuul-tests.yaml
#     extra-vars:
#       ansible_python_interpreter: /usr/bin/python3
#     nodeset:
#       nodes:
#         - name: test-node
#           label: cloud-fedora-31
