---
- name: This is a recipe for how to cook with packit_dashboard
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    packit_dashboard_path: /src/frontend
  tasks:
    - import_tasks: common.yaml
    - import_tasks: httpd.yaml

    - name: bundle javascript
      command:
        chdir: "{{ packit_dashboard_path }}"
        cmd: npm run build
