---
- name: This is a recipe for how to cook with packit_dashboard
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    packit_dashboard_path: /src
  tasks:
  - import_tasks: common.yaml
  - import_tasks: httpd.yaml

  - name: npm install
    npm:
      path: "{{ packit_dashboard_path }}"

