---
- name: Install dependencies for packit_dashboard.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run dashboard.
      dnf:
        name:
          - python3-pip
          - python3-flask
          - python3-requests
          - nss_wrapper
          - python3-pytest
          - python3-pytest-cov
          - make
        state: present
    - name: Install pip deps
      pip:
        name:
          - requre
        executable: pip3
  become: true
